/* jshint -W097 */
// jshint strict:false
/* jslint node: true */
/* jslint esversion: 6 */

"use strict";
const AIR_PURIFIER_INFORMATION = "info.";
const AIR_PURIFIER_CONTROL = "control.";
const AIR_PURIFIER_ERROR = "error";
const AIR_PURIFIER_POWER = "power";
const AIR_PURIFIER_MODE = "mode";
const AIR_PURIFIER_MODE_NIGHT = "night";
const AIR_PURIFIER_MODE_AUTO = "auto";
const AIR_PURIFIER_MODE_MANUAL = "manual";
const AIR_PURIFIER_MANUALLEVEL = "manuallevel";
const AIR_PURIFIER_TEMPERATURE = "temperature";
const AIR_PURIFIER_HUMIDITY = "humidity";
const AIR_PURIFIER_PM25 = "pm25";

module.exports = {
  AIR_PURIFIER_INFORMATION,
  AIR_PURIFIER_CONTROL,
  AIR_PURIFIER_ERROR,
  AIR_PURIFIER_POWER,
  AIR_PURIFIER_MODE,
  AIR_PURIFIER_MANUALLEVEL,
  AIR_PURIFIER_TEMPERATURE,
  AIR_PURIFIER_HUMIDITY,
  AIR_PURIFIER_PM25,
  AIR_PURIFIER_MODE_NIGHT,
  AIR_PURIFIER_MODE_AUTO,
  AIR_PURIFIER_MODE_MANUAL
};